//@refresh reset
import { createContext, useCallback, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';

export type Language = 'en' | 'id';

type TranslationDictionary = Record<string, string>;

const translations: Record<Language, TranslationDictionary> = {
  en: {
    nav_menu: 'Menu',
    menu_explore: 'Explore',
    menu_title: 'Our Menu',
    menu_items: 'items',
    menu_search_placeholder: 'Search drink, pastry, category...',
    menu_sort_recommended: 'Recommended',
    menu_sort_name: 'Name (A-Z)',
    menu_sort_price_low: 'Price (Low to High)',
    menu_sort_price_high: 'Price (High to Low)',
    menu_swipe_hint: 'Swipe categories, then tap a menu card to customize.',
    menu_empty_title: 'No items found.',
    menu_empty_description: 'Try another category, clear search, or change sorting.',
    menu_view_order: 'View Order',
    menu_product_add:'Add',
    menu_product_note:'Item Note',
    menu_product_note_ph:'E.g. Extra hot, separate sauce...',
    product_modal_add_to_cart: 'Add to Cart',
    product_modal_required_options: 'Select Required Options',
    product_modal_required: 'Required',
    home_tagline_title: 'Savour the',
    home_tagline_highlight: 'Moment.',
    home_tagline_desc: 'Experience the finest artisanal coffee, crafted with passion and precision. Join us for a journey of taste and tranquility.',
    home_order_now: 'Order Now',
    home_check_order: 'Check Order',
    home_login_signup: 'Login / Sign Up',
    home_favorites: 'Customer Favorites',
    home_weekly: 'Weekly Highlights',
    home_view_full_menu: 'View Full Menu',
    home_story_label: 'Our Story',
    home_story_title: 'Born in Malinau.',
    home_story_desc: 'What started as a small passion project in the heart of Malinau has grown into a sanctuary for coffee lovers. We believe that a cup of coffee is more than just caffeine—it\'s a moment of pause in a busy world.',
    home_happy_customers: 'Happy Customers',
    home_signature_blends: 'Signature Blends',
    home_visit_us: 'Visit Us',
    home_find_way: 'Find your way home.',
    home_opening_hours: 'Opening Hours',
    home_address: 'Address',
    home_footer_explore: 'Explore',
    home_footer_menu: 'Our Menu',
    home_footer_account: 'My Account',
    home_footer_contact: 'Contact',
    home_stay_connected: 'Stay Connected',
    home_stay_desc: 'Follow us for the latest brews and news.',
    home_check_modal_title: 'Check your order',
    home_check_modal_desc: 'Enter your order ID and phone number to open the order detail page.',
    home_order_id: 'Order ID',
    home_phone_number: 'Phone number',
    home_open_order_detail: 'Open Order Detail',
    home_checking: 'Checking...',
    home_ordered_count:'Ordered',
    cart_title: 'Your Order',
    cart_empty: 'Cart is empty',
    cart_edit: 'Edit',
    cart_note: 'Note',
    cart_subtotal: 'Subtotal',
    cart_checking_service: 'Checking service...',
    cart_unavailable: 'Online ordering unavailable',
    cart_checkout: 'Checkout',
    common_ordering_unavailable: "Sorry, Ulun currently can\'t take online orders.",
    checkout_title: 'Checkout',
    checkout_your_name: 'Your name',
    checkout_whatsapp: 'WhatsApp number',
    checkout_takeaway: 'Takeaway',
    checkout_delivery: 'Delivery',
    checkout_full_address: 'Full address',
    checkout_maps_link: 'Google Maps link',
    checkout_pinning: 'Pinning...',
    checkout_pin: 'Pin',
    checkout_order_notes: 'Order notes',
    checkout_promo_code: 'Promo code',
    checkout_apply: 'Apply',
    checkout_use_all_points: 'Use all points',
    checkout_summary: 'Order Summary',
    checkout_base: 'Base',
    checkout_subtotal: 'Subtotal',
    checkout_promo: 'Promo',
    checkout_points: 'Points',
    checkout_total: 'Total',
    checkout_processing: 'Processing...',
    checkout_checking_service: 'Checking order service...',
    checkout_place_order: 'Place Order',
    checkout_invalid_promo: 'Invalid promotion code',
    checkout_geo_not_supported: 'Geolocation not supported.',
    checkout_enter_name: 'Please enter your name.',
    checkout_enter_phone: 'Please enter your WhatsApp number.',
    checkout_add_address: 'Please add address or pin your location for delivery.',
    checkout_delivery_fee_note: 'Delivery fee is paid by the buyer directly to courier upon delivery.',
    checkout_ordering_retry: "Sorry, Ulun currently can't take online orders. Please try again in a few minutes.",
    checkout_back_menu: 'Back to menu',
    checkout_view_map: 'View pinned map',
    checkout_payment_success: 'Payment successful!',
    checkout_payment_waiting: 'Waiting for your payment!',
    checkout_payment_failed: 'Payment failed! Order cancelled.',
    checkout_payment_closed: 'You closed the popup without finishing the payment. Order cancelled.',
    order_detail_loading: 'Loading order details...',
    order_detail_not_found_title: 'Order not found',
    order_detail_not_found_desc: 'We could not find this order ID.',
    order_detail_back_home: 'Back to home',
    order_detail_recover_title: 'Recover your order page',
    order_detail_recover_desc: 'Enter your order ID and phone number to reopen your order details.',
    order_detail_order_id_placeholder: 'Order ID',
    order_detail_phone_placeholder: 'Phone number',
    order_detail_err_invalid_input: 'Please enter valid order ID and phone number.',
    order_detail_err_not_found: 'Order not found. Please recheck your input.',
    order_detail_err_mismatch: 'Order ID and phone number do not match.',
    order_detail_recovering: 'Recovering...',
    order_detail_recover_btn: 'Recover order',
    order_detail_leave_warning: 'If you leave this guest order page, you will need your order ID and phone number to recover it. Continue?',
    order_detail_toast_copied: 'Order ID copied.',
    order_detail_toast_copy_failed: 'Unable to copy order ID. Please copy manually.',
    order_detail_back: 'Back',
    order_detail_guest_warning: 'This is a guest order page. Please keep this page URL and stay on this page if possible. If closed, you can recover it using order ID and phone number.',
    order_detail_label: 'Order detail',
    order_detail_order: 'Order',
    order_detail_copy: 'Copy',
    order_detail_customer: 'Customer',
    order_detail_guest_customer: 'Guest customer',
    order_detail_total: 'Total',
    order_detail_items: 'Items',
    order_detail_fallback_item: 'Item',
    order_detail_quantity: 'Quantity',
    order_detail_base: 'Base',
    order_detail_item_unit: 'item',
    order_detail_note: 'Note',
    order_detail_unit: 'Unit',
    order_detail_subtotal: 'Subtotal',
    order_detail_no_items: 'No items found for this order.',
    order_status_pending: 'Pending',
    order_status_paid: 'Paid',
    order_status_active: 'Active',
    order_status_processing: 'Processing',
    order_status_completed: 'Completed',
    order_status_cancelled: 'Cancelled',
    order_detail_status_label: 'Current Status',
    admin_dashboard: 'Admin Dashboard',
    admin_tab_orders: 'Orders',
    admin_tab_products: 'Products',
    admin_tab_promotions: 'Promotions',
    admin_logout: 'Logout',
    
    // Admin - Orders
    admin_orders_search: 'Search by order ID, customer name, or item...',
    admin_orders_empty: 'No orders found.',
    admin_orders_type: 'Type:',
    admin_orders_total: 'Total:',
    admin_orders_address: 'Address:',
    admin_orders_view_map: 'View map',
    admin_status_pending: 'Pending',
    admin_status_assigned: 'Assigned',
    admin_status_completed: 'Completed',
    admin_status_cancelled: 'Cancelled',
    
    // Admin - Products Sidebar
    admin_prod_edit: 'Edit Product',
    admin_prod_add: 'Add Product',
    admin_prod_single: 'Single Item',
    admin_prod_bundle: 'Bundle',
    admin_prod_name: 'Product Name',
    admin_prod_bundle_contents: 'Bundle Contents',
    admin_prod_search_add: 'Search item to add...',
    admin_prod_no_match: 'No matching products found',
    admin_prod_pricing_strategy: 'Pricing Strategy',
    admin_prod_total_value: 'Total Value:',
    admin_prod_discount_pct: 'Discount %',
    admin_prod_final_price: 'Final Price',
    admin_prod_price: 'Price',
    admin_prod_category: 'Category',
    admin_prod_desc: 'Description',
    admin_prod_image_url: 'Image URL',
    admin_btn_cancel: 'Cancel',
    admin_btn_update: 'Update',
    admin_btn_create: 'Create',
    
    // Admin - Products List
    admin_prod_search: 'Search product by name, category, or description...',
    admin_prod_empty: 'No products found.',
    admin_action_edit_details: 'Edit Details',
    admin_action_manage_addons: 'Manage Add-ons',
    admin_action_remove_rec: 'Remove Recommended',
    admin_action_mark_rec: 'Mark Recommended',
    admin_action_archive: 'Archive',
    admin_action_restore: 'Restore',
    admin_action_delete_perm: 'Delete Permanently',
    admin_badge_archived: 'Archived',
    admin_badge_recommended: 'Recommended',
    admin_customizations_active: 'Customizations Active',
    
    // Admin - Promotions Form
    admin_promo_edit: 'Edit Promotion',
    admin_promo_new: 'New Promotion',
    admin_promo_code: 'CODE (e.g. SAVE20)',
    admin_promo_value: 'Value',
    admin_promo_type_pct: 'Percentage (%)',
    admin_promo_type_fixed: 'Fixed Amount (Rp)',
    admin_promo_scope_order: 'Entire Order',
    admin_promo_scope_category: 'Category',
    admin_promo_scope_product: 'Specific Product',
    admin_promo_search_cat: 'Search Category...',
    admin_promo_search_prod: 'Search Product...',
    admin_promo_no_results: 'No results found.',
    admin_promo_valid_from: 'Valid From (Optional)',
    admin_promo_valid_until: 'Valid Until (Optional)',
    admin_promo_clear_expiry: 'Clear Expiry Date',
    admin_promo_min_order: 'Min Order (Rp)',
    admin_promo_min_qty: 'Min Qty',
    admin_promo_btn_update: 'Update Promotion',
    admin_promo_btn_create: 'Create Promotion',
    
    // Admin - Promotions List
    admin_promo_empty: 'No promotions active.',
    admin_promo_deactivate: 'Deactivate',
    admin_promo_activate: 'Activate',
    admin_promo_off: 'OFF',
    admin_promo_no_expiry: '(No Expiry)',
    admin_action_edit: 'Edit',
    admin_action_delete: 'Delete',
    
    // Admin - General & Confirmations
    admin_confirm_delete_prod_title: 'Delete Product',
    admin_confirm_delete_prod_msg: 'Delete this product permanently? This cannot be undone.',
    admin_confirm_delete_promo_title: 'Delete Promotion',
    admin_confirm_delete_promo_msg: 'This will permanently delete this promotion code.',
    admin_confirm_are_you_sure: 'Are you sure?',
    admin_unknown: 'Unknown'
  },
  id: {
    nav_menu: 'Menu',
    menu_explore: 'Jelajahi',
    menu_title: 'Menu Kami',
    menu_items: 'item',
    menu_search_placeholder: 'Cari minuman, pastry, kategori...',
    menu_sort_recommended: 'Rekomendasi',
    menu_sort_name_asc: 'Nama (A-Z)',
    menu_sort_name_desc: 'Nama (Z-A)',
    menu_sort_price_low: 'Harga (Rendah ke Tinggi)',
    menu_sort_price_high: 'Harga (Tinggi ke Rendah)',
    menu_swipe_hint: 'Geser kategori, lalu ketuk menu untuk kustomisasi.',
    menu_empty_title: 'Tidak ada item ditemukan.',
    menu_empty_description: 'Coba kategori lain, hapus pencarian, atau ubah urutan.',
    menu_view_order: 'Lihat Pesanan',
    menu_product_add:'Tambah',
    menu_product_note:'Nota Item',
    menu_product_note_ph:'misal:  tambahkan saus, pisahkan sambal...',
    product_modal_add_to_cart: 'Tambah ke Keranjang',
    product_modal_required_options: 'Isi Pilihan Wajib',
    product_modal_required: 'Wajib',
    home_tagline_title: 'Nikmati',
    home_tagline_highlight: 'Momen.',
    home_tagline_desc: 'Rasakan kopi artisanal terbaik, yang dibuat dengan penuh gairah dan ketelitian. Bergabunglah bersama kami dalam perjalanan cita rasa dan ketenangan.',
    home_order_now: 'Pesan Sekarang',
    home_check_order: 'Cek Pesanan',
    home_login_signup: 'Masuk / Daftar',
    home_favorites: 'Favorit Pelanggan',
    home_weekly: 'Sorotan Mingguan',
    home_view_full_menu: 'Lihat Semua Menu',
    home_story_label: 'Cerita Kami',
    home_story_title: 'Lahir di Malinau.',
    home_story_desc: 'Berawal dari proyek kecil penuh passion di jantung Malinau, kini tumbuh menjadi tempat nyaman bagi pecinta kopi. Bagi kami, secangkir kopi bukan sekadar kafein—ini adalah jeda di tengah dunia yang sibuk.',
    home_happy_customers: 'Pelanggan',
    home_signature_blends: 'Signature Blend',
    home_visit_us: 'Kunjungi Kami',
    home_find_way: 'Temukan jalan ke Ulun.',
    home_opening_hours: 'Jam Operasional',
    home_address: 'Alamat',
    home_footer_explore: 'Jelajahi',
    home_footer_menu: 'Menu Kami',
    home_footer_account: 'Akun Saya',
    home_footer_contact: 'Kontak',
    home_stay_connected: 'Tetap Terhubung',
    home_stay_desc: 'Ikuti kami untuk kabar terbaru seputar racikan dan berita.',
    home_check_modal_title: 'Cek pesananmu',
    home_check_modal_desc: 'Masukkan ID pesanan dan nomor telepon untuk membuka detail pesanan.',
    home_order_id: 'ID Pesanan',
    home_phone_number: 'Nomor telepon',
    home_open_order_detail: 'Cari Pesanan',
    home_checking: 'Memeriksa...',
    home_ordered_count:'Pesanan',
    cart_title: 'Pesanan Kamu',
    cart_empty: 'Keranjang kosong',
    cart_edit: 'Ubah',
    cart_note: 'Catatan',
    cart_subtotal: 'Subtotal',
    cart_checking_service: 'Memeriksa layanan...',
    cart_unavailable: 'Pemesanan online tidak tersedia',
    cart_checkout: 'Checkout',
    common_ordering_unavailable: 'Maaf, Ulun saat ini belum bisa menerima pesanan online.',
    checkout_title: 'Checkout',
    checkout_your_name: 'Nama kamu',
    checkout_whatsapp: 'Nomor WhatsApp',
    checkout_takeaway: 'Ambil Sendiri',
    checkout_delivery: 'Diantar',
    checkout_full_address: 'Alamat lengkap',
    checkout_maps_link: 'Link Google Maps',
    checkout_pinning: 'Menandai...',
    checkout_pin: 'Pin',
    checkout_order_notes: 'Catatan pesanan',
    checkout_promo_code: 'Kode promo',
    checkout_apply: 'Pakai',
    checkout_use_all_points: 'Gunakan semua poin',
    checkout_summary: 'Ringkasan Pesanan',
    checkout_base: 'Harga dasar',
    checkout_subtotal: 'Subtotal',
    checkout_promo: 'Promo',
    checkout_points: 'Poin',
    checkout_total: 'Total',
    checkout_processing: 'Memproses...',
    checkout_checking_service: 'Memeriksa layanan pesanan...',
    checkout_place_order: 'Buat Pesanan',
    checkout_invalid_promo: 'Kode promo tidak valid',
    checkout_geo_not_supported: 'Geolocation tidak didukung.',
    checkout_enter_name: 'Silakan isi nama kamu.',
    checkout_enter_phone: 'Silakan isi nomor WhatsApp kamu.',
    checkout_add_address: 'Tambahkan alamat atau pin lokasi untuk pengantaran.',
    checkout_delivery_fee_note: 'Biaya antar dibayar langsung oleh pembeli ke kurir saat pengantaran.',
    checkout_ordering_retry: 'Maaf, Ulun saat ini belum bisa menerima pesanan online. Silakan coba lagi beberapa menit lagi.',
    checkout_back_menu: 'Kembali ke menu',
    checkout_view_map: 'Lihat peta yang dipin',
    checkout_payment_success: 'Pembayaran berhasil!',
    checkout_payment_waiting: 'Menunggu pembayaran kamu!',
    checkout_payment_failed: 'Pembayaran gagal! Pesanan dibatalkan.',
    checkout_payment_closed: 'Kamu menutup popup sebelum menyelesaikan pembayaran. Pesanan dibatalkan.',
    order_detail_loading: 'Memuat detail pesanan...',
    order_detail_not_found_title: 'Pesanan tidak ditemukan',
    order_detail_not_found_desc: 'Kami tidak dapat menemukan ID pesanan ini.',
    order_detail_back_home: 'Kembali ke beranda',
    order_detail_recover_title: 'Pulihkan halaman pesanan Anda',
    order_detail_recover_desc: 'Masukkan ID pesanan dan nomor telepon Anda untuk membuka kembali detail pesanan Anda.',
    order_detail_order_id_placeholder: 'ID Pesanan',
    order_detail_phone_placeholder: 'Nomor telepon',
    order_detail_err_invalid_input: 'Harap masukkan ID pesanan dan nomor telepon yang valid.',
    order_detail_err_not_found: 'Pesanan tidak ditemukan. Harap periksa kembali masukan Anda.',
    order_detail_err_mismatch: 'ID Pesanan dan nomor telepon tidak cocok.',
    order_detail_recovering: 'Memulihkan...',
    order_detail_recover_btn: 'Pulihkan pesanan',
    order_detail_leave_warning: 'Jika Anda meninggalkan halaman pesanan tamu ini, Anda akan memerlukan ID pesanan dan nomor telepon untuk memulihkannya. Lanjutkan?',
    order_detail_toast_copied: 'ID Pesanan berhasil disalin.',
    order_detail_toast_copy_failed: 'Tidak dapat menyalin ID pesanan. Harap salin secara manual.',
    order_detail_back: 'Kembali',
    order_detail_guest_warning: 'Ini adalah halaman pesanan tamu. Harap simpan URL halaman ini dan tetap di halaman ini jika memungkinkan. Jika ditutup, Anda dapat memulihkannya menggunakan ID pesanan dan nomor telepon.',
    order_detail_label: 'Detail pesanan',
    order_detail_order: 'Pesanan',
    order_detail_copy: 'Salin',
    order_detail_customer: 'Pelanggan',
    order_detail_guest_customer: 'Pelanggan tamu',
    order_detail_total: 'Total',
    order_detail_items: 'Item',
    order_detail_fallback_item: 'Item',
    order_detail_quantity: 'Jumlah',
    order_detail_base: 'Harga dasar',
    order_detail_item_unit: 'item',
    order_detail_note: 'Catatan',
    order_detail_unit: 'Harga satuan',
    order_detail_subtotal: 'Subtotal',
    order_detail_no_items: 'Tidak ada item yang ditemukan untuk pesanan ini.',
    order_status_pending: 'Pending',
    order_status_paid: 'Paid',
    order_status_active: 'Active',
    order_status_processing: 'Processing',
    order_status_completed: 'Completed',
    order_status_cancelled: 'Cancelled',
    order_detail_status_label: 'Status Saat Ini',
    admin_dashboard: 'Dashboard Admin',
    admin_tab_orders: 'Pesanan',
    admin_tab_products: 'Produk',
    admin_tab_promotions: 'Promosi',
    admin_logout: 'Keluar',
    
    // Admin - Orders
    admin_orders_search: 'Cari berdasarkan ID pesanan, nama, atau item...',
    admin_orders_empty: 'Tidak ada pesanan ditemukan.',
    admin_orders_type: 'Tipe:',
    admin_orders_total: 'Total:',
    admin_orders_address: 'Alamat:',
    admin_orders_view_map: 'Lihat peta',
    admin_status_pending: 'Pending',
    admin_status_assigned: 'Assigned',
    admin_status_completed: 'Completed',
    admin_status_cancelled: 'Cancelled',
    
    // Admin - Products Sidebar
    admin_prod_edit: 'Edit Produk',
    admin_prod_add: 'Tambah Produk',
    admin_prod_single: 'Single',
    admin_prod_bundle: 'Paket (Bundle)',
    admin_prod_name: 'Nama Produk',
    admin_prod_bundle_contents: 'Isi Paket',
    admin_prod_search_add: 'Cari item untuk ditambahkan...',
    admin_prod_no_match: 'Produk tidak ditemukan',
    admin_prod_pricing_strategy: 'Strategi Harga',
    admin_prod_total_value: 'Total Nilai:',
    admin_prod_discount_pct: 'Diskon %',
    admin_prod_final_price: 'Harga Akhir',
    admin_prod_price: 'Harga',
    admin_prod_category: 'Kategori',
    admin_prod_desc: 'Deskripsi',
    admin_prod_image_url: 'URL Gambar',
    admin_btn_cancel: 'Batal',
    admin_btn_update: 'Perbarui',
    admin_btn_create: 'Buat',
    
    // Admin - Products List
    admin_prod_search: 'Cari produk berdasarkan nama, kategori, atau deskripsi...',
    admin_prod_empty: 'Tidak ada produk ditemukan.',
    admin_action_edit_details: 'Edit Detail',
    admin_action_manage_addons: 'Kelola Add-on',
    admin_action_remove_rec: 'Hapus Rekomendasi',
    admin_action_mark_rec: 'Tandai Rekomendasi',
    admin_action_archive: 'Arsipkan',
    admin_action_restore: 'Pulihkan',
    admin_action_delete_perm: 'Hapus Permanen',
    admin_badge_archived: 'Diarsipkan',
    admin_badge_recommended: 'Rekomendasi',
    admin_customizations_active: 'Add-ons Aktif',
    
    // Admin - Promotions Form
    admin_promo_edit: 'Edit Promosi',
    admin_promo_new: 'Promosi Baru',
    admin_promo_code: 'KODE (mis. DISKON20)',
    admin_promo_value: 'Nilai',
    admin_promo_type_pct: 'Persentase (%)',
    admin_promo_type_fixed: 'Nominal Tetap (Rp)',
    admin_promo_scope_order: 'Seluruh Pesanan',
    admin_promo_scope_category: 'Kategori',
    admin_promo_scope_product: 'Produk Spesifik',
    admin_promo_search_cat: 'Cari Kategori...',
    admin_promo_search_prod: 'Cari Produk...',
    admin_promo_no_results: 'Tidak ada hasil.',
    admin_promo_valid_from: 'Berlaku Dari (Opsional)',
    admin_promo_valid_until: 'Berlaku Sampai (Opsional)',
    admin_promo_clear_expiry: 'Hapus Tanggal Berakhir',
    admin_promo_min_order: 'Min Pembelian (Rp)',
    admin_promo_min_qty: 'Min Kuantitas',
    admin_promo_btn_update: 'Perbarui Promosi',
    admin_promo_btn_create: 'Buat Promosi',
    
    // Admin - Promotions List
    admin_promo_empty: 'Tidak ada promosi aktif.',
    admin_promo_deactivate: 'Nonaktifkan',
    admin_promo_activate: 'Aktifkan',
    admin_promo_off: 'POTONGAN',
    admin_promo_no_expiry: '(Tanpa Kadaluarsa)',
    admin_action_edit: 'Edit',
    admin_action_delete: 'Hapus',
    
    // Admin - General & Confirmations
    admin_confirm_delete_prod_title: 'Hapus Produk',
    admin_confirm_delete_prod_msg: 'Hapus produk ini secara permanen? Tindakan ini tidak dapat dibatalkan.',
    admin_confirm_delete_promo_title: 'Hapus Promosi',
    admin_confirm_delete_promo_msg: 'Ini akan menghapus kode promosi secara permanen.',
    admin_confirm_are_you_sure: 'Apakah Anda yakin?',
    admin_unknown: 'Tidak diketahui'
  }
};

type LanguageContextValue = {
  language: Language;
  setLanguage: (lang: Language) => void;
  toggleLanguage: () => void;
  t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const stored = localStorage.getItem('app_language');
    return stored === 'id' ? 'id' : 'en';
  });

  useEffect(() => {
    localStorage.setItem('app_language', language);
    document.documentElement.lang = language === 'id' ? 'id' : 'en';
  }, [language]);

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
  }, []);

  const toggleLanguage = useCallback(() => {
    setLanguageState((prev) => (prev === 'en' ? 'id' : 'en'));
  }, []);

  const t = useCallback(
    (key: string) => {
      return translations[language][key] || translations.en[key] || key;
    },
    [language]
  );

  const value = useMemo(
    () => ({ language, setLanguage, toggleLanguage, t }),
    [language, setLanguage, toggleLanguage, t]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}